[tool.poetry]
name = "poptimizer"
version = "3.0.0"
description = "Portfolio optimization"
authors = ["WLMike <wlmike@gmail.com>"]
license = "The Unlicense"
readme = "README.md"
repository = "https://github.com/WLM1ke/poptimizer"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
motor = "^3.0.0"
aiomoex = "^2.0.0"
openpyxl = "^3.0.10"
pydantic = "^1.9.2"
uvloop = "^0.17.0"
aiofiles = "^22.1.0"
types-aiofiles = "^22.1.0"
lxml = "^4.9.1"
pandas = "^1.5.0"
torch = "^1.13.0"

[tool.poetry.group.dev.dependencies]
import-linter = {extras = ["toml"], version = "^1.3.0"}
wemake-python-styleguide = "^0.17.0"
mypy = "^0.991"
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
black = {extras = ["d"], version = "^22.6.0"}

[tool.poetry.scripts]
poptimizer="poptimizer.__main__:main"

[tool.mypy]
plugins = [
    "pydantic.mypy"
]

strict = true
ignore_missing_imports = true
warn_unreachable = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true

[tool.coverage.run]
branch = true

[tool.coverage.report]
exclude_lines = ["if __name__ == .__main__.:"]
omit = ["*/tests/*"]

[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.importlinter]
root_package = "poptimizer"

[[tool.importlinter.contracts]]
name = "Layered"
type = "layers"
layers = [
    "poptimizer.app",
    "poptimizer.utils",
    "poptimizer.server",
    "poptimizer.portfolio",
    "poptimizer.data",
    "poptimizer.core",
]
ignore_imports = [
    "poptimizer.data.update.raw.status -> poptimizer.portfolio.adapter",
    "poptimizer.server.logger -> poptimizer.utils.lgr",
    "poptimizer.data.update.quotes -> poptimizer.utils.retry",
]

[[tool.importlinter.contracts]]
name = "Weakly coupled middle layer"
type = "independence"
modules = [
    "poptimizer.server",
    "poptimizer.portfolio",
    "poptimizer.data",
]
ignore_imports = [
    "poptimizer.data.*.*.* -> poptimizer.*.adapter",
    "poptimizer.portfolio.*.* -> poptimizer.*.adapter",
    "poptimizer.server.* -> poptimizer.*.edit.*",
    "poptimizer.server.middleware -> poptimizer.*.exceptions",
]
