version: "3"

vars:
  APP: poptimizer
  PYTHON: 3.11
  TOOLS: go-task pdm

dotenv: [".env"]

tasks:
  default:
    desc: List available tasks.
    cmds:
      - task -l

  setup:
    desc: Install {{.TOOLS | replace " " ", "}}, python{{.PYTHON}} and dependencies. Setup venv.
    cmds:
      - brew install {{.TOOLS}} python@{{.PYTHON}}
      - python{{.PYTHON}} -m venv --clear .venv
      - task: update

  update:
    desc: Upgrade {{.TOOLS | replace " " ", "}}, python{{.PYTHON}} and dependencies.
    cmds:
      - brew upgrade {{.TOOLS}} python@{{.PYTHON}}
      - pdm update --update-all --no-sync
      - pdm sync --clean
      - pdm update --dry-run --unconstrained

  lint:
    desc: Format black and isort. Lint lint-imports, mypy and wemake-python-styleguide.
    cmds:
      - pdm run black {{.APP}}
      - pdm run isort {{.APP}}
      - pdm run lint-imports
      - pdm run mypy {{.APP}}
      - pdm run flake8p {{.APP}}

  test:
    desc: Lint and test with pytest.
    deps: [lint]
    cmds:
      - pdm run pytest {{.APP}} --cov={{.APP}}

  run:
    desc: Run {{.APP}} with .env file.
    cmds:
      - .venv/bin/python -m {{.APP}}
